import React from 'react';
import { Header } from './';
import Head from 'next/head';

function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Vintager</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      {children}
    </div>
  );
}

export default Layout;
